cast-org/clusive

frontend/js/frontend.js
This is a temporary fix for the image load detection check for the images within the library cards and if they should be in 'portrait' mode.  
The upstream fix was made in Figuration, and will be included in the next release. This patch can then be removed when the package dependencies are updated.
=> NOJIRA: Implement temp fix for portrait image detection

requirements.txt, src/clusive_project/settings.py, src/internal.js, src/shared/templates/shared/partial/head_scripts.html
I know Alan has some ideas on how to handle reducing the console output, but wanted to toss this out there.
This might work to reduce most of the console output from both the Fluid and JS sides.
Concept uses Django's `DEBUG` setting as master setting to enable/disable.
This no-op method (while potentially inefficient) allows the console.log to be re-enabled in production if some remote debugging is needed.
~Still need to investigate how to pass this into the Readium frame.~
Thoughts?
=> CSL-187: No-op console.log() when not in debug mode

src/frontend/js/frontend.js, src/frontend/scss/.stylelintrc, src/frontend/scss/mixins/_site-theme.scss, src/frontend/scss/site-themes/_theme-default.scss, src/frontend/scss/site-themes/_theme-night.scss, src/frontend/scss/site-themes/_theme-sepia.scss, src/frontend/scss/site/_content.scss, src/frontend/scss/site/_setting.scss
Currently part of CSL-400. Prototype example of adding 'tooltip' or visible value label to range inputs.
Included a 'callback' feature so tips can be updated on a case by case basis.
Will have to reconsider if it should be exposed to screen-readers instead of being hidden.
=> CSL-450: Add 'tooltip' to range slider

src/frontend/js/clusive-prefs-django-store.js, src/roster/views.py
* Reset now working with new message queue implementation
* Remove the `beforeunload` event until it can be made to work only on logout (see https://castudl.atlassian.net/browse/CSL-463)
=> CSL-297: preference reset for message queue implementation

src/frontend/html/library.html, src/frontend/html/modal.html, src/frontend/html/reader.html, src/frontend/html/roster.html, src/frontend/html/wordbank.html, src/frontend/js/frontend.js, src/frontend/js/tts.js, src/frontend/scss/mixins/_site-theme.scss, src/frontend/scss/site-themes/_theme-default.scss, src/frontend/scss/site-themes/_theme-night.scss, src/frontend/scss/site-themes/_theme-sepia.scss, src/frontend/scss/site/_button.scss, src/frontend/scss/site/_setting.scss, src/frontend/scss/site/_sidebar.scss, src/frontend/scss/site/_site-post.scss, src/frontend/scss/site/_site-pre.scss, src/shared/templates/shared/partial/modal_settings.html, src/shared/templates/shared/partial/sidebar_end.html
Adds state swapping for the TTS button in the sidebar, along with Pause and Resume controls.  Works for the most part with the ClusiveTTS, but there does seem to be some lag when using pause/resume, but I don't think there is much we can do there.
Tried to build in support multiple regions of TTS controls, such as a preview one in the settings modal. Does not take into account reading selected text from context menu since it is Reader controlled.
Probably going to need some form of callback from the Reader to update state when play is started or stopped.
=> CSL-455:  TTS control update

package-lock.json, package.json, src/frontend/html/index.html, src/frontend/js/clusive-prefs-modal-settings.js, src/frontend/js/frontend.js, src/frontend/js/theme-test.js, src/frontend/scss/clusive.scss, src/frontend/scss/mixins/_line-height.scss, src/frontend/scss/site/_card.scss, src/frontend/scss/site/_content.scss, src/frontend/scss/site/_footer.scss, src/frontend/scss/site/_goal.scss, src/frontend/scss/site/_library.scss, src/frontend/scss/site/_popover.scss, src/frontend/scss/site/_site-pre.scss, src/frontend/scss/site/_site.scss, src/frontend/scss/site/_wordbank.scss, src/shared/templates/shared/partial/modal_settings.html
Normalizes the `line-height` (line spacing) visuals between the Clusive and Readium sides.
Internal names for the line-height have been adjusted to align the `1.6` option as `default`, changing from the `1.2` option marked as such.  I don't think additional changes are needed since `1.6` is the default setting, unless there is a test that needs to be updated.
=> CSL-309: Update line height

src/frontend/js/tts.js
This only affects the Clusive side of TTS, and most likely only for iOS.
This method uses a regex match to find the word boundary and start of next word to determine highlight.
Android/Chrome does not seem to support `utternance.onboundary` at the moment.
https://bugs.chromium.org/p/chromium/issues/detail?id=521666
=> NOJIRA: Add alternative method for TTS highlighting

src/frontend/js/clusive-context.js, src/frontend/js/clusive-events-caliper.js, src/frontend/js/page-timing.js, src/frontend/js/tts.js, src/index.js, src/shared/templates/shared/partial/head_scripts.html
This moves all current scripts into the Webpack-generated main.js file.
Due to Webpack's conventions, this required some minimal refactoring to explicitly place some referenced globals on the `window` object, and wrap some code execution in `$(document).ready()` to avoid reliance on script load order.
=> CSL-438: consolidate header scripts into main.js

src/eventlog/signals.py, src/frontend/js/clusive-events-caliper.js, src/frontend/js/toc.js, src/glossary/templates/glossary/glossdef.html, src/messagequeue/models.py, src/pages/templates/pages/wordbank.html, src/shared/templates/shared/partial/modal_toc.html, src/shared/templates/shared/partial/modal_why.html, src/shared/templates/shared/partial/sidebar_start.html
This PR handles the addition of event tracking for a number of JIRAs that are child issues of the main CSL-350 event logging JIRA at https://castudl.atlassian.net/browse/CSL-350
Specifically, it should address:
- https://castudl.atlassian.net/browse/CSL-355
- https://castudl.atlassian.net/browse/CSL-356
- https://castudl.atlassian.net/browse/CSL-365
- https://castudl.atlassian.net/browse/CSL-366
- https://castudl.atlassian.net/browse/CSL-367
- https://castudl.atlassian.net/browse/CSL-368
- https://castudl.atlassian.net/browse/CSL-369
- https://castudl.atlassian.net/browse/CSL-370
- https://castudl.atlassian.net/browse/CSL-371
In some cases these were a straightforward matter of using the `data-cle-*`  annotation style to add event logging to markup that is available when the page loads, …
=> Various event logging JIRAs

INSTALL.md
Small change to `INSTALL.md` warning users to not use python version 3.9 or higher.
=> NOJIRA: Added note about not using python 3.9.x

src/frontend/js/clusive-django-message-queue.js, src/pages/templates/pages/debug.html
This fixes the bug with minimal changes to the existing code:
- adds a singleton component (`logoutFlushManager`) to track the number of flushes at logout and compare them against the number of `djangoMessageQueues`, which are now registered with the manager at creation
- do not perform the logout until the expected number of queues have been flushed (the bug was because there are now two separate message queues, and whichever one called back first caused the logout before the other could fush)
Longer-term, I'd like to move all "flush on logout" behaviour into the manager component, but that can be a separate JIRA.
=> bugfix/CSL-721: not all queues being flushed on logout as intended

src/roster/models.py, src/roster/templates/roster/manage.html, src/roster/views.py
Allows self-created Teacher/Parent accounts to create classes, create students for them, and assign readings.
On the back end, creates a personal `Site` for a parent/teacher account when they first try to add a new class. This is necessary with the current model.
=> CSL-809: handle zero-class scenarios for self-created Teacher/Parent accounts

src/clusive_project/urls.py
This should block crawlers that respect `robots.txt` from following any `/account` URLs, including the guest login.
Found at https://stackoverflow.com/questions/18424260/django-serving-robots-txt-efficiently, which suggests serving `robots.txt` as a static file, but I'm uncertain of our static file server configuration in production, and this should be fine for now given our traffic levels.
=> CSL-917: generate robots.txt file blocking /account

INSTALL.md, local_install.ps1, local_install.sh
Adds build scripts to automate away (most) of the steps for setting up or refreshing a local dev environment.
I've tested these myself (using WSL to test the `.sh` on my Windows machine), but if someone using a Mac can confirm the `.sh` script works for them, I think we can merge this and make people's lives a bit easier.
=> CSL-945: add build scripts

src/assessment/models.py, src/assessment/urls.py, src/assessment/views.py, src/frontend/js/assessment.js, src/frontend/js/clusive-autosave.js, src/index.js, src/messagequeue/models.py, src/shared/templates/shared/partial/popover_comp.html
This implements a general autosave pattern using the existing message queue system, and uses it to replace the manual save in the assessments pop-up.
Key files:
- `frontend/js/clusive-autosave.js`: provides an autosave interface with `save` and `retrieve` methods that use REST-ful URLs as keys (using code doesn't need to know if it's dealing with local or server data)
- `frontend/js/assessments.js`: uses the autosave code
- `messagequeue/models.py`: uses `django.urls.resolve` to match REST-ful URLs to appropriate View methods
- `assessments/views.py`: extracts `create_from_request` methods used by the autosave code
=> CSL-944: autosave

src/clusive_project/settings.py
@bgoldowsky - ready for review.
This was much easier than anticipated -- I expected to have to fiddle with the database, but it's just one line in the settings.  Anyway, it's done, unless you see something I missed.
JIRA: https://castudl.atlassian.net/browse/CSL-1010
=> CSL-1010: Remove Google classroom roster scope from SSO sign-up

src/frontend/js/clusive-reader-prefs.js
Small change (thanks @mbrambilla for identifying) that fixes several reported bug in preference application.
Should fix the following reported bugs (tested on dev environment):
- https://castudl.atlassian.net/browse/CSL-1089
- https://castudl.atlassian.net/browse/CSL-1090
- https://castudl.atlassian.net/browse/CSL-1091
- https://castudl.atlassian.net/browse/CSL-995
- https://castudl.atlassian.net/browse/CSL-996
=> CSL-1089: make readerPreferencesBridge user settings application nullsafe

src/eventlog/signals.py, src/eventlog/views.py, src/pages/views.py
Opening PR for discussion in tech meeting tomorrow, I think this is a simple possible solution to https://castudl.atlassian.net/browse/CSL-1092, but it needs to be validated as acceptable from a research statistics standpoint.
The high level change is that Page Timing events (sent from the client-side message queue system) now add their time to the `duration` and `active_duration` fields of an existing Event, rather than simply being rejected. The `load_time` field remains fixed to capture the initial render time of the page from the server.
Functionally, this means using the 'back' button or other means to return to a page via the browser history will generate additional duration and active duration for the initial page view event, but not a second page view event.
Questions:
- is this …
=> CSL-1092: page timing event tracking when using browser-cached page

src/roster/urls.py
Possible fix for the server error reported in [CSL-1088](https://castudl.atlassian.net/browse/CSL-1088).
I ran into a similar problem when trying to change the password of one of my test accounts in my development environment, where the stack trace indicated a missing authentication backend.  This PR fixes that by specifying Django's `django.contrib.auth.backends.ModelBackend`.
=> CSL-1088: Fix change-password authentication backend

src/frontend/js/clusive-prefs-modal-settings.js, src/frontend/js/tts.js, src/shared/templates/shared/partial/modal_settings.html
New implementation:
-  Assume base language of `en`
-  Check user/browser languages for region specific `en-*` variants - default to first voice on match based on order of preference - as reported by `navigator.languages`
- otherwise default to first `en-US` voice
- default to first `en` voice if no `en-US` voice available
-  Remove the 'Choose…' option from list since we are forcing a voice
I think it should cover most of our current/intended user base - there could be some issues for international users - but most language related-items are already hard-coded to an `en` base.  Testing on my environments seems to be working well otherwise.
=> CSL-1370: Force a default TTS voice

src/frontend/js/clusive-prefs-modal-settings.js, src/frontend/js/clusive-prefs-panel.js, src/roster/fixtures/preferencesets.json, src/roster/tests.py, src/shared/templates/shared/partial/modal_settings.html
@bgoldowsky @mbrambilla Here are the changes to the former "Reduce motion" switch, inverting it to "Animations (on/off)"
JIRA decision: https://castudl.atlassian.net/browse/CSL-1409?focusedCommentId=31635 and https://castudl.atlassian.net/browse/CSL-1409?focusedCommentId=31636
=> Add reduce motion preference

src/library/views.py
Re-configures the error message to be of the form `Error: <Bookshare's error message(s)>`, for example: `Error: Search term is too short`.
Ready for review.
=> CSL-1412: Improve error message when Bookshare search returns an error

src/library/views.py
Python 3.8 warns against using `is` and `is not` for comparisons involving
literals such as `0` (zero), and requires the use of `==` or `!=` instead.
See:
https://adamj.eu/tech/2020/01/21/why-does-python-3-8-syntaxwarning-for-is-literal/
=> NOJIRA: Resolve python `SyntaxWarning` for `is not`; use `!=` instead.

src/frontend/js/frontend.js, src/library/templates/library/list_customizations.html, src/library/templates/library/partial/modal_delete_customization.html
Implemented the ability to delete a customization to the page that lists all of the customizations associated with an article:
- `Delete this Customization` buttons for each customization on the page,
- Confirmation popup dialog to allow user to confirm or cancel the deletion.
The UI is there for testing the implementation and could use some loving.
JIRA: https://castudl.atlassian.net/browse/CSL-1582
=> CSL-1582: Implement deletion of a customization.

src/library/templates/library/partial/library_collection_selector.html, src/library/views.py, src/roster/models.py
Questions: 
Starred books are not immediately taken out of the Starred List - view is not refreshed (could change mind and the book is gone).  Is this the correct behavior?
What is the order of the filter?  Order is: period, starred, public, my, all.  Is this ok?
Similar to my books, starred is a filter even when there are no starred readings.  Is this ok?
=> CS-1646 Add starred filter for library books

src/frontend/js/clusive-reader-prefs.js, src/frontend/scss/site/_content.scss, src/pages/templates/pages/reader.html, src/shared/templates/shared/partial/head_styles.html
Android and iOS devices do not have a Comic font in their base install, this adds the Google Font 'Comic Neue' to the font stack
https://fonts.google.com/specimen/Comic+Neue
=> CSL-1750: Add 'Comic Neue' for users without 'Comic Sans'

src/library/templates/library/partial/library_card.html, src/library/templates/library/partial/library_card_list.html, src/library/templates/library/partial/library_teacher_extra_info.html
Fixed the duplication and normalized the layout for the menu button across card variants.
If a reading has not been assigned or customized the menu will appear next to the topics.  Once assigned or customized the menu button will be under the divider and next to the assigned/customized indicators.
=> CSL-1690: Fix visuals and duplication of action menu on library cards

src/frontend/js/toc.js, src/pages/templates/pages/reader.html, src/shared/templates/shared/partial/modal_toc.html, src/shared/templates/shared/partial/sidebar_start.html
Replaces #226
Note that NVDA tries to be smart when `role="dialog" items close/hide. NVDA forces focus back to the TOC button upon close of modal, even though Figuration is not doing so, but the focus does get moved properly into the reader frame.
VoiceOver focus seems to move directly into the reader frame without a brief layover on the TOC button.
=> CSL-1515: TOC and Highlight items move focus to reader when clicked

src/frontend/js/.eslintrc.json, src/frontend/js/page-timing.js
- "Handle" negative `active_duration` in PageTiming by setting it to zero. 
- Detect and use `PerformanceNavigationTiming` API for getting load times if available.
JIRA: https://castudl.atlassian.net/browse/CSL-1553
=> CSL-1533 Prevent negative active time from getting recorded

src/frontend/js/shortcut.js, src/frontend/js/tts.js, src/shared/templates/shared/partial/modal_settings.html, src/shared/templates/shared/partial/modal_toc.html, src/shared/templates/shared/partial/popover_simplify.html
Stop TTS is changing tab in the dialog where TTS is currently speaking.
Also adds some `id`s to some tab triggers for consistency.
=> CSL-1828+1830: Stop TTS on tab change

src/library/models.py, src/library/parsing.py, src/pages/templates/pages/reader.html, src/pages/views.py
This adds a `make_positions_and_weight()` function that is used during book import that adds content length to the reading order items in Clusive's `manifest.json`, and generates the `positions.json` and `weight.json` files.
A problem was found with two of the epubs from Clusive's public content.  One was the `tocqueville_democracy-vol1.pub`, in the `gutenberg-tocqueville-democracy-vol1` folder.  The other was volume two.  Volume one's meta-data, and consequently the manifest's reading order, include a link to `../_public_vhost_g_gutenberg_html_files_815_815-h_815-h-19_appendix.xhtml`.  But there is no such entry in the zipfile.
In that case, the `contentLength` for the reading order item in the manifest is left out, and no position nor weight is calculated for it.  I'm not sure if that …
=> CSL-1872: Improve load times

src/frontend/html/popover.html, src/frontend/js/tour.js, src/frontend/scss/mixins/_site-theme.scss, src/frontend/scss/site-themes/_theme-default.scss, src/frontend/scss/site-themes/_theme-night.scss, src/frontend/scss/site-themes/_theme-sepia.scss, src/frontend/scss/site/_popover.scss, src/frontend/scss/site/_site-pre.scss, src/index.js
Base layout and styling for tour popovers, also referred to as the 'tooltip' tour.
Contains basic chaining functionality to move between popovers through the use of CSS selectors.  The selectors used in the function calls refer to the trigger element even though the triggers will not actually invoke the show/hide of the popover. The 'trigger' will be where the 'arrow' portion of the popover will point to.  
Currently each popover needs to be initialized through the `tour.prepare(selector)`.
A 'start tour' button will be used to begin the tour, and movement through the chain will be controlled through links in each popover, using `tour.chain(selector)`.   Included is a a customized close routine, `tour.closeRefocus(selector)` to close the popover tour and return focus to a specified …
=> CSL-1930: Mockup tour popovers, chaining code
